Added Several Debug Leds
ToolboxPlane/FlightControllerBoard pull request #3
Opened 2017-04-22 18:49 UTC by aul12

Added LEDs for SBUS, UART and I²C

2017-04-22 20:32 UTC, ottojo requested changes
Please remove lock files as well

2017-04-22 20:42 UTC, ottojo requested changes
Please change label style to the one used in the schematic,
Remove broken Via at 35,5/38mm
Change Via type to octagon
Route N$4 N$5 (RX/TX LEDs)
Fix LED Silkscreen

2017-04-23 07:48 UTC, aul12 commented
Fixed in 5d06181fe69a45b403068e5a7ec4f3a47d7302ba

2017-04-23 11:24 UTC, ottojo approved these changes

2017-04-23 11:24 UTC, merged